server:
  port: 8081


spring:
  application:
    name: cloud-payment-service
  datasource:
    ds1:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://101.200.220.160:3306/recruitment?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
    ds2:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://101.200.220.160:3306/recruitment?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
  mail:
    password: jkrouwkwpbazbajj #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    host: smtp.qq.com  #发送邮件服务器
    properties.mail.smtp.port: 465  #端口号465或587
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    username: 603943860@qq.com

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: cn.zlx.bs.bean

#配置email